[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "agroecometrics"
version = "0.0.2b2"
description = "This package contains useful tools for Agriculture and Ecological researchers to clean, manipulate, display, and convert data."
authors = [
    { name = "Scarlett Olson", email = "Scarlett.Olson@wisc.edu" }
]
license = { text = "MIT" }
requires-python = ">=3.6"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scipy",
    "mpl_toolkits.mtlot3d",
    "seaborn"
]

[project.urls]
Homepage = "https://github.com/wiscbicklab/AgroEcoMetrics"
Issues = "https://github.com/wiscbicklab/AgroEcoMetrics/issues"

[tool.setuptools.packages.find]
include = ["agroecometrics", "agroecometrics.*"]
